version: '3.8'
services:
  client:
    extends:
      file: services/client-service.yml
      service: client
  db:
    extends:
      file: services/db-service.yml
      service: db
    env_file:
      - ./environment/.env.dev
  restore:
    extends:
      file: services/restore-service.yml
      service: restore
    env_file:
      - ./environment/.env.dev

volumes:
  db_data: