version: '3.8'

services:
  db:
    extends:
      file: services/db-service.yml
      service: db
    env_file:
      - ./environment/.env.dev
    networks:
      - backend

  restore:
    extends:
      file: services/restore-service.yml
      service: restore
    env_file:
      - ./environment/.env.dev
    depends_on:
      - db
    networks:
      - backend

  finances:
    extends:
      file: services/api/finances-service.yml
      service: finances
    env_file:
      - ./environment/.env.dev
    depends_on:
      - db
    networks:
      - backend

  project:
    extends:
      file: services/api/project-service.yml
      service: project
    env_file:
      - ./environment/.env.dev
    depends_on:
      - db
    networks:
      - backend

  client:
    extends:
      file: services/client-service.yml
      service: client
    networks:
      - frontend
    depends_on:
      - db

  nginx:
    extends:
      file: services/nginx-service.yml
      service: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - finances
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend:

volumes:
  db_data:
