version: '3.8'

services:
  db:
    extends:
      file: services/db-service.yml
      service: db
    env_file:
      - ./environment/.env.dev

  restore:
    extends:
      file: services/restore-service.yml
      service: restore
    env_file:
      - ./environment/.env.dev
    depends_on:
      - db

  finances:
    extends:
      file: services/api/finances-service.yml
      service: finances
    depends_on:
      - db

  task:
    extends:
      file: services/api/task-service.yml
      service: task
    depends_on:
      - db

  client:
    extends:
      file: services/client-service.yml
      service: client
    ports:
      - "5000:80"
    depends_on:
      - db

  nginx:
    extends:
      file: services/nginx-service.yml
      service: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - finances
      - task

volumes:
  db_data:
