#!/bin/bash

# Vérifie si Docker Compose est installé
if ! command -v docker-compose &> /dev/null; then
    echo "Docker Compose n'est pas installé sur ce système."
    exit 1
fi

# Votre commande Docker Compose
# Lire les variables d'environnement à partir du fichier .env.dev et les exporter
export $(cat ./environment/.env.dev | xargs)

# Spécifier les fichiers Docker Compose que vous souhaitez utiliser
docker_compose_files=(
  -f docker-compose.yml
#   -f ./services/client-service.yml
  -f ./services/db-service.yml
  -f ./services/restore-service.yml
#   -f ./services/nginx-service.yml
  -f ./services/api/finances-service.yml
#   -f ./services/api/task-service.yml
)

# Utiliser docker-compose avec les fichiers spécifiés
docker-compose "${docker_compose_files[@]}" up

# Autres commandes Docker Compose que vous souhaitez exécuter
# docker-compose ...

# Fin du script
