version: '3.8'
services:
  finances:
    container_name: srv_finances
    image: timgnh/finances:latest 
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8080

