version: '3.8'
services:
  project:
    container_name: srv_project
    image: timgnh/project:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8080

